# Generated by Django 3.1.3 on 2020-11-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0006_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='images',
            field=models.ImageField(default='', upload_to='jobs/'),
            preserve_default=False,
        ),
    ]
