# Generated by Django 3.1.3 on 2020-11-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0010_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='Created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
