# Generated by Django 3.1.3 on 2020-11-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0011_apply_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='webiste',
            new_name='website',
        ),
    ]
