# Generated by Django 3.1.3 on 2020-12-25 18:58

import Job.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0013_job_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='images',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[500, 300], upload_to=Job.models.image_upload),
        ),
    ]
